call index_pushDaReForecastFromRemcApi.exe
call index_pushChattSolarForecastData.exe
@REM call index_downloadRemcDaForecastExcel.exe
@REM call index_pushDaReForecastData.exe
@REM call index_updateGujSolarForeWithStateGenFile.exe
@REM call index_updateGjReForecastToSdl.exe
