index_pushIntradayReForecastFromRemcApiRealtime.exe

@REM call index_downloadRemcIntradayForecastExcel.exe
@REM call index_pushIntradayReForecastData.exe
@REM call index_updateGujSolarForeWithStateGenFile.exe
