create table re_forecast
(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
time_stamp date,
entity_tag varchar2(100),
revision_no varchar2(3CHAR),
reforecasted_value number,
constraints unique_reforecast unique(time_stamp,entity_tag,revision_no),
constraints pk_reforecast primary key(id)
)